var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// ../app/src/data/books.tsx
var books_exports = {};
__export(books_exports, {
  BOOKS: () => BOOKS,
  CATEGORIES: () => CATEGORIES,
  byCategory: () => byCategory,
  discountPct: () => discountPct,
  formatINR: () => formatINR,
  getBook: () => getBook
});
module.exports = __toCommonJS(books_exports);
var import_lucide_react = require("lucide-react");
var rv = (user, rating, title, body, date) => ({
  id: Math.random().toString(36).slice(2, 9),
  user,
  rating,
  title,
  body,
  date,
  verified: true
});
var CATEGORIES = [
  { slug: "competitive-exams", name: "Competitive Exam", icon: /* @__PURE__ */ React.createElement(import_lucide_react.Trophy, { className: "w-4 h-4" }) },
  { slug: "medical", name: "Medical", icon: /* @__PURE__ */ React.createElement(import_lucide_react.Stethoscope, { className: "w-4 h-4" }) },
  { slug: "engineering", name: "Engineering", icon: /* @__PURE__ */ React.createElement(import_lucide_react.Settings, { className: "w-4 h-4" }) },
  { slug: "school", name: "NCERT / ICSE", icon: /* @__PURE__ */ React.createElement(import_lucide_react.Backpack, { className: "w-4 h-4" }) },
  { slug: "university", name: "University", icon: /* @__PURE__ */ React.createElement(import_lucide_react.GraduationCap, { className: "w-4 h-4" }) },
  { slug: "fiction", name: "Fiction", icon: /* @__PURE__ */ React.createElement(import_lucide_react.BookOpen, { className: "w-4 h-4" }) },
  { slug: "non-fiction", name: "Non-Fiction", icon: /* @__PURE__ */ React.createElement(import_lucide_react.Lightbulb, { className: "w-4 h-4" }) },
  { slug: "bengali", name: "Bengali Story", icon: /* @__PURE__ */ React.createElement(import_lucide_react.Flower2, { className: "w-4 h-4" }) },
  { slug: "international", name: "International", icon: /* @__PURE__ */ React.createElement(import_lucide_react.Globe2, { className: "w-4 h-4" }) },
  { slug: "rare", name: "Rare", icon: /* @__PURE__ */ React.createElement(import_lucide_react.Gem, { className: "w-4 h-4" }) },
  { slug: "techno-world", name: "Our Publications", icon: /* @__PURE__ */ React.createElement(import_lucide_react.Building2, { className: "w-4 h-4" }) }
];
var BOOKS = [
  {
    id: "b01",
    slug: "rich-dad-poor-dad",
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    publisher: "Plata Publishing",
    isbn: "9781612680194",
    edition: "2nd Edition",
    pubDate: "2017-04-11",
    language: "English",
    pages: 336,
    category: "non-fiction",
    tags: ["finance", "money", "investing", "bestseller"],
    price: 299,
    mrp: 499,
    rating: 4.6,
    ratingsCount: 48210,
    stock: 42,
    bestseller: true,
    trending: true,
    coverHue: 268,
    description: "Rich Dad Poor Dad is Robert Kiyosaki's story of growing up with two dads \u2014 his real father and the father of his best friend, his rich dad \u2014 and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you need to earn a high income to be rich and explains the difference between working for money and having your money work for you.",
    toc: ["The Rich Don't Work for Money", "Why Teach Financial Literacy?", "Mind Your Own Business", "The History of Taxes", "The Rich Invent Money", "Work to Learn \u2014 Don't Work for Money"],
    reviews: [rv("Ankit Sharma", 5, "Life changing", "Completely changed how I think about money and assets. A must read for every student.", "2025-11-02"), rv("Priya Menon", 4, "Great primer", "Simple language, powerful ideas. Some parts feel repetitive but worth it.", "2025-09-18")]
  },
  {
    id: "b02",
    slug: "atomic-habits",
    title: "Atomic Habits",
    author: "James Clear",
    publisher: "Penguin Random House",
    isbn: "9781847941831",
    edition: "1st Edition",
    pubDate: "2018-10-16",
    language: "English",
    pages: 320,
    category: "non-fiction",
    tags: ["habits", "self-help", "productivity"],
    price: 449,
    mrp: 699,
    rating: 4.8,
    ratingsCount: 65432,
    stock: 61,
    bestseller: true,
    trending: true,
    coverHue: 20,
    description: "No matter your goals, Atomic Habits offers a proven framework for improving \u2014 every day. James Clear reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    toc: ["The Fundamentals", "The 1st Law: Make It Obvious", "The 2nd Law: Make It Attractive", "The 3rd Law: Make It Easy", "The 4th Law: Make It Satisfying", "Advanced Tactics"],
    reviews: [rv("Rahul Verma", 5, "Practical and actionable", "The habit stacking technique genuinely works. Finished it twice.", "2025-12-10")]
  },
  {
    id: "b03",
    slug: "the-alchemist",
    title: "The Alchemist",
    author: "Paulo Coelho",
    publisher: "HarperOne",
    isbn: "9780062315007",
    edition: "25th Anniversary Edition",
    pubDate: "2014-04-15",
    language: "English",
    pages: 208,
    category: "fiction",
    tags: ["classic", "philosophical", "journey"],
    price: 249,
    mrp: 399,
    rating: 4.5,
    ratingsCount: 38900,
    stock: 55,
    bestseller: true,
    coverHue: 42,
    description: "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different \u2014 and far more satisfying \u2014 than he ever imagined.",
    toc: ["Part One", "Part Two", "Epilogue"],
    reviews: [rv("Sneha Iyer", 5, "Beautiful", "A fable about following your dreams. Reads like poetry.", "2025-08-22")]
  },
  {
    id: "b04",
    slug: "ncert-physics-class-12",
    title: "NCERT Physics Part I & II \u2014 Class 12",
    author: "NCERT",
    publisher: "NCERT",
    isbn: "9788174506313",
    edition: "2024 Edition",
    pubDate: "2024-03-01",
    language: "English",
    pages: 590,
    category: "school",
    tags: ["ncert", "cbse", "class 12", "physics", "boards"],
    price: 320,
    mrp: 340,
    rating: 4.7,
    ratingsCount: 15230,
    stock: 120,
    exam: "CBSE Boards",
    course: "Class 12",
    semester: "Annual",
    coverHue: 200,
    description: "Official NCERT Physics textbook for Class 12 (Part I & II), the foundational book for CBSE board exams, JEE and NEET. Covers electrostatics, current electricity, magnetism, optics, modern physics and more.",
    toc: ["Electric Charges and Fields", "Electrostatic Potential", "Current Electricity", "Moving Charges and Magnetism", "Ray Optics", "Wave Optics", "Dual Nature of Radiation", "Atoms and Nuclei", "Semiconductor Electronics"],
    reviews: [rv("Aditya Kumar", 5, "Genuine NCERT", "Original print, crisp pages, delivered in 2 days.", "2026-01-15")]
  },
  {
    id: "b05",
    slug: "rd-sharma-mathematics-class-12",
    title: "Mathematics Class 12 (Volume 1 & 2)",
    author: "R.D. Sharma",
    publisher: "Dhanpat Rai Publications",
    isbn: "9789383182372",
    edition: "2025-26 Edition",
    pubDate: "2025-04-01",
    language: "English",
    pages: 1350,
    category: "school",
    tags: ["mathematics", "cbse", "class 12", "jee"],
    price: 745,
    mrp: 995,
    rating: 4.6,
    ratingsCount: 9840,
    stock: 34,
    bestseller: true,
    exam: "CBSE Boards",
    course: "Class 12",
    coverHue: 220,
    description: "The most trusted reference book for Class 12 Mathematics. Exhaustive theory with graded examples and practice problems \u2014 ideal for CBSE boards and JEE Main preparation.",
    toc: ["Relations and Functions", "Inverse Trigonometric Functions", "Matrices", "Determinants", "Continuity and Differentiability", "Integrals", "Differential Equations", "Vector Algebra", "Probability"],
    reviews: [rv("Ishita Roy", 5, "Best for boards + JEE", "Huge question bank. Solved examples are gold.", "2025-10-05")]
  },
  {
    id: "b06",
    slug: "concepts-of-physics-hc-verma",
    title: "Concepts of Physics Vol. 1 & 2",
    author: "H.C. Verma",
    publisher: "Bharati Bhawan",
    isbn: "9788177091878",
    edition: "Latest Edition",
    pubDate: "2023-01-10",
    language: "English",
    pages: 950,
    category: "engineering",
    tags: ["physics", "jee", "neet", "conceptual"],
    price: 599,
    mrp: 860,
    rating: 4.8,
    ratingsCount: 22100,
    stock: 48,
    bestseller: true,
    trending: true,
    exam: "JEE",
    course: "Physics",
    coverHue: 160,
    description: "H.C. Verma's Concepts of Physics is the bible for JEE and NEET aspirants. Crystal-clear theory paired with thought-provoking objective and subjective problems that build rock-solid fundamentals.",
    toc: ["Kinematics", "Newton's Laws of Motion", "Work and Energy", "Rotational Mechanics", "Gravitation", "Simple Harmonic Motion", "Waves", "Heat and Thermodynamics", "Electrostatics", "Magnetic Field"],
    reviews: [rv("Karan Singh", 5, "JEE essential", "If you can solve HCV, JEE physics becomes easy.", "2025-11-30")]
  },
  {
    id: "b07",
    slug: "objective-mathematics-rd-sharma-jee",
    title: "Objective Mathematics for JEE Main & Advanced",
    author: "R.D. Sharma",
    publisher: "Dhanpat Rai",
    isbn: "9789386182047",
    edition: "2025 Edition",
    pubDate: "2025-05-01",
    language: "English",
    pages: 1420,
    category: "competitive-exams",
    tags: ["jee", "mathematics", "objective"],
    price: 899,
    mrp: 1295,
    rating: 4.5,
    ratingsCount: 6120,
    stock: 25,
    exam: "JEE",
    trending: true,
    coverHue: 250,
    description: "Comprehensive objective-type question bank for JEE Main & Advanced with previous year questions, topic-wise MCQs and detailed solutions.",
    toc: ["Algebra", "Trigonometry", "Coordinate Geometry", "Calculus", "Vectors & 3D", "Probability & Statistics", "Previous Year Papers"],
    reviews: [rv("Mohit Agarwal", 4, "Solid practice", "Massive collection of problems with good solutions.", "2025-12-01")]
  },
  {
    id: "b08",
    slug: "neet-physics-chemistry-biology-40-years",
    title: "NEET 40 Years Chapterwise Solved Papers (PCB)",
    author: "Arihant Experts",
    publisher: "Arihant Publications",
    isbn: "9789325299161",
    edition: "2025 Edition",
    pubDate: "2025-06-01",
    language: "English",
    pages: 1680,
    category: "competitive-exams",
    tags: ["neet", "previous year", "solved papers"],
    price: 950,
    mrp: 1490,
    rating: 4.6,
    ratingsCount: 8450,
    stock: 39,
    bestseller: true,
    exam: "NEET",
    newRelease: true,
    coverHue: 350,
    description: "Complete chapterwise and topicwise solved papers of 40 years of NEET/AIPMT for Physics, Chemistry and Biology with detailed explanations, NCERT references and trend analysis.",
    toc: ["Physics: Mechanics to Modern Physics", "Chemistry: Physical, Organic, Inorganic", "Biology: Botany & Zoology", "NEET 2025 Paper with Solutions", "Trend Analysis Charts"],
    reviews: [rv("Nandini Das", 5, "Perfect for NEET prep", "Solutions map to NCERT lines. Extremely useful.", "2026-01-08")]
  },
  {
    id: "b09",
    slug: "mtg-neet-guide-biology",
    title: "NEET Guide \u2014 Biology",
    author: "MTG Editorial Board",
    publisher: "MTG Learning Media",
    isbn: "9789395551197",
    edition: "2025-26",
    pubDate: "2025-07-01",
    language: "English",
    pages: 1220,
    category: "competitive-exams",
    tags: ["neet", "biology", "ncert"],
    price: 825,
    mrp: 1100,
    rating: 4.5,
    ratingsCount: 5230,
    stock: 44,
    exam: "NEET",
    coverHue: 130,
    description: "Complete NEET Biology guide covering the entire NCERT syllabus with theory, NCERT-based MCQs, assertion-reason questions and previous year questions.",
    toc: ["The Living World", "Cell: The Unit of Life", "Genetics and Evolution", "Human Physiology", "Plant Physiology", "Biotechnology", "Ecology"],
    reviews: [rv("Farhan Ali", 4, "Very NCERT aligned", "Great for last-mile revision.", "2025-11-19")]
  },
  {
    id: "b10",
    slug: "upsc-indian-polity-laxmikanth",
    title: "Indian Polity",
    author: "M. Laxmikanth",
    publisher: "McGraw Hill",
    isbn: "9789354602586",
    edition: "7th Edition",
    pubDate: "2024-08-01",
    language: "English",
    pages: 1024,
    category: "competitive-exams",
    tags: ["upsc", "polity", "civil services"],
    price: 695,
    mrp: 1050,
    rating: 4.8,
    ratingsCount: 31400,
    stock: 58,
    bestseller: true,
    exam: "UPSC",
    coverHue: 10,
    description: "The definitive book on Indian Polity for UPSC Civil Services and State PSC examinations. Covers the Constitution, governance, Parliament, judiciary and local government with unmatched clarity.",
    toc: ["Constitutional Framework", "Union Government", "State Government", "Local Government", "Judiciary", "Constitutional Bodies", "Amendments & Schedules"],
    reviews: [rv("Deepika Nair", 5, "UPSC bible", "One book to rule polity. The 7th edition is updated with latest amendments.", "2025-10-27")]
  },
  {
    id: "b11",
    slug: "quantitative-aptitude-rs-aggarwal",
    title: "Quantitative Aptitude",
    author: "R.S. Aggarwal",
    publisher: "S. Chand",
    isbn: "9789352835860",
    edition: "Revised Edition",
    pubDate: "2023-01-01",
    language: "English",
    pages: 960,
    category: "competitive-exams",
    tags: ["aptitude", "banking", "ssc", "placement"],
    price: 540,
    mrp: 795,
    rating: 4.5,
    ratingsCount: 27600,
    stock: 73,
    bestseller: true,
    exam: "SSC / Banking",
    coverHue: 190,
    description: "The evergreen aptitude book for every competitive exam \u2014 SSC, banking, railways, campus placements. 6000+ questions with fully worked solutions.",
    toc: ["Number System", "Percentage", "Profit and Loss", "Time and Work", "Time, Speed and Distance", "Data Interpretation", "Algebra", "Geometry"],
    reviews: [rv("Saurabh Yadav", 5, "One-stop for quant", "Solved fully for my SBI PO prep. Highly recommended.", "2025-09-09")]
  },
  {
    id: "b12",
    slug: "grays-anatomy-students",
    title: "Gray's Anatomy for Students",
    author: "Richard Drake, A. Wayne Vogl",
    publisher: "Elsevier",
    isbn: "9780323934237",
    edition: "5th Edition",
    pubDate: "2024-02-15",
    language: "English",
    pages: 1168,
    category: "medical",
    tags: ["anatomy", "mbbs", "first year"],
    price: 4299,
    mrp: 6800,
    rating: 4.9,
    ratingsCount: 4820,
    stock: 15,
    bestseller: true,
    course: "MBBS",
    semester: "1st Year",
    university: "MCI/NMC Curriculum",
    coverHue: 5,
    description: "The most student-friendly anatomy textbook, fully revised with clinical case boxes, imaging correlations and surface anatomy \u2014 ideal for MBBS first year.",
    toc: ["The Body", "Back", "Thorax", "Abdomen", "Pelvis and Perineum", "Lower Limb", "Upper Limb", "Head and Neck"],
    reviews: [rv("Dr. Meera Krishnan", 5, "Best anatomy text", "Clinical boxes make anatomy stick. Fast delivery, sealed pack.", "2025-12-19")]
  },
  {
    id: "b13",
    slug: "robbins-basic-pathology",
    title: "Robbins Basic Pathology",
    author: "Vinay Kumar, Abul Abbas",
    publisher: "Elsevier",
    isbn: "9780323661178",
    edition: "11th Edition",
    pubDate: "2023-04-01",
    language: "English",
    pages: 928,
    category: "medical",
    tags: ["pathology", "mbbs", "second year"],
    price: 3850,
    mrp: 5600,
    rating: 4.8,
    ratingsCount: 3910,
    stock: 12,
    course: "MBBS",
    semester: "2nd Year",
    trending: true,
    coverHue: 330,
    description: "The gold standard pathology text for medical students, covering general and systemic pathology with superb illustrations and clinical correlations.",
    toc: ["Cell Injury and Death", "Inflammation and Repair", "Neoplasia", "Hemodynamic Disorders", "Diseases of Organ Systems", "Infectious Diseases"],
    reviews: [rv("Arjun Reddy", 5, "Pathology simplified", "Papa Robbins never disappoints. Original edition confirmed.", "2025-11-11")]
  },
  {
    id: "b14",
    slug: "harrisons-internal-medicine",
    title: "Harrison's Principles of Internal Medicine (2 Vols)",
    author: "Dennis Kasper et al.",
    publisher: "McGraw Hill",
    isbn: "9781264268504",
    edition: "21st Edition",
    pubDate: "2023-03-01",
    language: "English",
    pages: 4300,
    category: "medical",
    tags: ["medicine", "mbbs", "pg", "reference"],
    price: 14500,
    mrp: 21e3,
    rating: 4.9,
    ratingsCount: 2340,
    stock: 6,
    course: "MBBS",
    semester: "Final Year",
    rare: true,
    coverHue: 280,
    description: "The most trusted textbook of internal medicine worldwide. Two-volume set with 4,300 pages of authoritative, evidence-based clinical content.",
    toc: ["Cardinal Manifestations of Disease", "Pharmacology", "Oncology", "Cardiology", "Pulmonology", "Gastroenterology", "Nephrology", "Neurology", "Infectious Disease"],
    reviews: [rv("Dr. Vikram Sethi", 5, "The reference", "Essential for final year and PG prep.", "2025-08-15")]
  },
  {
    id: "b15",
    slug: "bd-chaurasia-human-anatomy",
    title: "B.D. Chaurasia's Human Anatomy (4 Vols)",
    author: "B.D. Chaurasia",
    publisher: "CBS Publishers",
    isbn: "9789354662177",
    edition: "9th Edition",
    pubDate: "2024-01-01",
    language: "English",
    pages: 1800,
    category: "medical",
    tags: ["anatomy", "mbbs", "indian author"],
    price: 2399,
    mrp: 3400,
    rating: 4.7,
    ratingsCount: 7610,
    stock: 22,
    course: "MBBS",
    semester: "1st Year",
    bestseller: true,
    coverHue: 90,
    description: "India's most widely used anatomy textbook set for MBBS. Clear line diagrams, exam-oriented text, and clinical anatomy sections in every chapter.",
    toc: ["Vol 1: Upper Limb & Thorax", "Vol 2: Lower Limb, Abdomen & Pelvis", "Vol 3: Head, Neck & Brain", "Vol 4: General Anatomy & Embryology"],
    reviews: [rv("Tanvi Joshi", 5, "Exam saviour", "Every anatomy viva answer is in here.", "2025-10-02")]
  },
  {
    id: "b16",
    slug: "engineering-mathematics-bs-grewal",
    title: "Higher Engineering Mathematics",
    author: "B.S. Grewal",
    publisher: "Khanna Publishers",
    isbn: "9788174091955",
    edition: "44th Edition",
    pubDate: "2022-01-01",
    language: "English",
    pages: 1320,
    category: "engineering",
    tags: ["mathematics", "btech", "gate"],
    price: 650,
    mrp: 925,
    rating: 4.6,
    ratingsCount: 12800,
    stock: 47,
    bestseller: true,
    course: "B.Tech",
    semester: "1st-2nd Year",
    exam: "GATE",
    coverHue: 210,
    description: "The standard engineering mathematics text used across Indian universities \u2014 calculus, linear algebra, differential equations, complex analysis, numerical methods and probability.",
    toc: ["Differential Calculus", "Integral Calculus", "Linear Algebra", "Differential Equations", "Complex Analysis", "Laplace Transforms", "Numerical Methods", "Probability & Statistics"],
    reviews: [rv("Nikhil Patil", 4, "University essential", "Covers the entire B.Tech math syllabus.", "2025-09-25")]
  },
  {
    id: "b17",
    slug: "data-structures-cormen-algorithms",
    title: "Introduction to Algorithms (CLRS)",
    author: "Thomas H. Cormen, et al.",
    publisher: "MIT Press",
    isbn: "9780262046305",
    edition: "4th Edition",
    pubDate: "2022-04-05",
    language: "English",
    pages: 1312,
    category: "engineering",
    tags: ["algorithms", "computer science", "dsa"],
    price: 1250,
    mrp: 1895,
    rating: 4.7,
    ratingsCount: 8940,
    stock: 31,
    course: "B.Tech CSE",
    semester: "2nd-3rd Year",
    trending: true,
    coverHue: 0,
    description: "The definitive algorithms textbook covering sorting, data structures, graph algorithms, dynamic programming, NP-completeness and advanced topics. Essential for CS students and interview prep.",
    toc: ["Foundations", "Sorting and Order Statistics", "Data Structures", "Advanced Design Techniques", "Graph Algorithms", "NP-Completeness", "Approximation Algorithms"],
    reviews: [rv("Shreya Gupta", 5, "The CLRS", "Dense but complete. My go-to for placement prep.", "2025-12-14")]
  },
  {
    id: "b18",
    slug: "strength-of-materials-timoshenko",
    title: "Strength of Materials",
    author: "Timoshenko & Gere",
    publisher: "CBS Publishers",
    isbn: "9788123910980",
    edition: "3rd Edition",
    pubDate: "2021-01-01",
    language: "English",
    pages: 780,
    category: "engineering",
    tags: ["mechanical", "civil", "som"],
    price: 575,
    mrp: 795,
    rating: 4.5,
    ratingsCount: 4210,
    stock: 28,
    course: "B.Tech Mech/Civil",
    coverHue: 35,
    description: "Classic treatment of mechanics of materials \u2014 stress, strain, bending, torsion, deflection and columns with rigorous derivations and engineering applications.",
    toc: ["Tension and Compression", "Shear and Bending", "Torsion", "Deflection of Beams", "Columns", "Energy Methods"],
    reviews: [rv("Rohit Chauhan", 4, "Solid theory", "The derivations are beautiful. Great for GATE too.", "2025-08-30")]
  },
  {
    id: "b19",
    slug: "wings-of-fire-kalam",
    title: "Wings of Fire: An Autobiography",
    author: "A.P.J. Abdul Kalam",
    publisher: "Universities Press",
    isbn: "9788173711466",
    edition: "Reprint",
    pubDate: "1999-01-01",
    language: "English",
    pages: 196,
    category: "non-fiction",
    tags: ["biography", "inspiration", "india"],
    price: 199,
    mrp: 350,
    rating: 4.7,
    ratingsCount: 29500,
    stock: 88,
    bestseller: true,
    coverHue: 25,
    description: "The autobiography of Dr. A.P.J. Abdul Kalam \u2014 from Rameswaram to Rashtrapati Bhavan. A story of perseverance, science and service to the nation.",
    toc: ["Orientation", "Creation", "Propitiation", "Contemplation", "Epilogue"],
    reviews: [rv("Ananya Bose", 5, "Inspiring", "Every Indian student should read this.", "2025-11-05")]
  },
  {
    id: "b20",
    slug: "sapiens-yuval-noah-harari",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    publisher: "Harper",
    isbn: "9780062316097",
    edition: "1st Edition",
    pubDate: "2015-02-10",
    language: "English",
    pages: 464,
    category: "non-fiction",
    tags: ["history", "anthropology", "science"],
    price: 425,
    mrp: 699,
    rating: 4.6,
    ratingsCount: 34100,
    stock: 39,
    trending: true,
    coverHue: 45,
    description: "How did Homo sapiens come to dominate the world? Harari explores the Cognitive, Agricultural and Scientific Revolutions that shaped humanity \u2014 provocative, sweeping and unputdownable.",
    toc: ["The Cognitive Revolution", "The Agricultural Revolution", "The Unification of Humankind", "The Scientific Revolution", "The End of Homo Sapiens"],
    reviews: [rv("Kabir Malhotra", 5, "Mind-expanding", "Changed how I see money, nations and religion.", "2025-10-19")]
  },
  {
    id: "b21",
    slug: "the-psychology-of-money",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    publisher: "Jaico Publishing",
    isbn: "9789390166268",
    edition: "1st Edition",
    pubDate: "2020-09-08",
    language: "English",
    pages: 256,
    category: "non-fiction",
    tags: ["finance", "behavior", "investing"],
    price: 289,
    mrp: 399,
    rating: 4.7,
    ratingsCount: 41200,
    stock: 67,
    bestseller: true,
    trending: true,
    coverHue: 150,
    description: "Doing well with money has surprisingly little to do with how smart you are and a lot to do with how you behave. Through 19 short stories, Housel explores the strange ways people think about wealth, greed and happiness.",
    toc: ["No One's Crazy", "Luck & Risk", "Never Enough", "Confounding Compounding", "Getting Wealthy vs. Staying Wealthy", "Save, Just Save", "Freedom"],
    reviews: [rv("Divya Rathi", 5, "Best finance book", "Short chapters, deep lessons. Bought copies for friends.", "2025-12-22")]
  },
  {
    id: "b22",
    slug: "one-indian-girl-chetan-bhagat",
    title: "One Indian Girl",
    author: "Chetan Bhagat",
    publisher: "Rupa Publications",
    isbn: "9788129142146",
    edition: "1st Edition",
    pubDate: "2016-10-01",
    language: "English",
    pages: 280,
    category: "fiction",
    tags: ["romance", "indian fiction", "contemporary"],
    price: 185,
    mrp: 299,
    rating: 4.1,
    ratingsCount: 18900,
    stock: 52,
    coverHue: 320,
    description: "Meet Radhika Mehta \u2014 a high-flying investment banker who is about to get married, but two ex-boyfriends show up at her destination wedding. A witty take on love, ambition and modern Indian relationships.",
    toc: ["Prologue: The Wedding", "The Banker", "The Ex Files", "The Choice", "Epilogue"],
    reviews: [rv("Pooja Hegde", 4, "Fun read", "Finished on one train journey. Classic Chetan Bhagat.", "2025-07-12")]
  },
  {
    id: "b23",
    slug: "half-girlfriend-chetan-bhagat",
    title: "Half Girlfriend",
    author: "Chetan Bhagat",
    publisher: "Rupa Publications",
    isbn: "9788129135728",
    edition: "1st Edition",
    pubDate: "2014-10-01",
    language: "English",
    pages: 260,
    category: "fiction",
    tags: ["romance", "indian fiction"],
    price: 175,
    mrp: 250,
    rating: 4,
    ratingsCount: 21400,
    stock: 44,
    coverHue: 300,
    description: `Madhav Jha, a boy from Bihar, falls for Riya Somani, a rich Delhi girl, at St. Stephen's College. She agrees to be his "half girlfriend". A rural-urban love story that became a Bollywood film.`,
    toc: ["Patna", "Delhi", "The Half Girlfriend", "New York", "The Journal"],
    reviews: [rv("Amit Kumar", 4, "Easy read", "Simple English, good for beginners.", "2025-06-18")]
  },
  {
    id: "b24",
    slug: "the-guide-rk-narayan",
    title: "The Guide",
    author: "R.K. Narayan",
    publisher: "Indian Thought Publications",
    isbn: "9788185986074",
    edition: "Reprint",
    pubDate: "1958-01-01",
    language: "English",
    pages: 248,
    category: "fiction",
    tags: ["classic", "indian literature", "malgudi"],
    price: 225,
    mrp: 325,
    rating: 4.6,
    ratingsCount: 9800,
    stock: 26,
    coverHue: 55,
    description: "Raju the tourist guide becomes an unwilling holy man in this Sahitya Akademi Award-winning novel from the creator of Malgudi. A masterpiece of irony and transformation.",
    toc: ["Raju the Guide", "Rosie", "Marco", "The Cave", "The Famine"],
    reviews: [rv("Sunita Rao", 5, "Timeless", "The ending still gives me chills.", "2025-09-14")]
  },
  {
    id: "b25",
    slug: "feluda-samagra-satyajit-ray",
    title: "Feluda Samagra (Vol 1 & 2)",
    author: "Satyajit Ray",
    publisher: "Ananda Publishers",
    isbn: "9788177565033",
    edition: "Collected Edition",
    pubDate: "2015-01-01",
    language: "Bengali",
    pages: 1500,
    category: "bengali",
    tags: ["feluda", "detective", "satyajit ray", "bengali"],
    price: 1100,
    mrp: 1500,
    rating: 4.9,
    ratingsCount: 12700,
    stock: 18,
    bestseller: true,
    coverHue: 75,
    description: "\u09B8\u09A4\u09CD\u09AF\u099C\u09BF\u09CE \u09B0\u09BE\u09AF\u09BC\u09C7\u09B0 \u09B8\u0995\u09B2 \u09E9\u09EB\u099F\u09BF \u09AB\u09C7\u09B2\u09C1\u09A6\u09BE \u0997\u09B2\u09CD\u09AA\u09C7\u09B0 \u09B8\u09AE\u09CD\u09AA\u09C2\u09B0\u09CD\u09A3 \u09B8\u0982\u0995\u09B2\u09A8 \u2014 The complete collection of all 35 Feluda detective stories by Satyajit Ray. A treasure for every Bengali reader.",
    toc: ["\u09AC\u09A6\u09B6\u09BE\u09B9\u09BF \u0985\u0982\u099F\u09BF", "\u09B2\u09A8\u09CD\u09A1\u09A8\u09C7 \u09AB\u09C7\u09B2\u09C1\u09A6\u09BE", "\u09B8\u09CB\u09A8\u09BE\u09B0 \u0995\u09C7\u09B2\u09CD\u09B2\u09BE", "\u099C\u09AF\u09BC \u09AC\u09BE\u09AC\u09BE \u09AB\u09C7\u09B2\u09C1\u09A8\u09BE\u09A5", "\u0997\u09CB\u09B0\u09B8\u09CD\u09A5\u09BE\u09A8\u09C7 \u09B8\u09BE\u09AC\u09A7\u09BE\u09A8", "\u09B0\u09AC\u09BE\u09B0\u09CD\u099F\u09B8\u09A8\u09C7\u09B0 \u09B0\u09C1\u09AC\u09BF"],
    reviews: [rv("Anirban Chatterjee", 5, "\u0985\u09B8\u09BE\u09A7\u09BE\u09B0\u09A3 \u09B8\u0982\u0995\u09B2\u09A8", "\u099B\u09C7\u09B2\u09C7\u09AC\u09C7\u09B2\u09BE\u09B0 \u09B8\u09CD\u09AE\u09C3\u09A4\u09BF\u0964 \u099B\u09BE\u09AA\u09BE\u09B0 \u09AE\u09BE\u09A8 \u099A\u09AE\u09CE\u0995\u09BE\u09B0\u0964", "2025-11-28")]
  },
  {
    id: "b26",
    slug: "srikanta-sarat-chandra",
    title: "Srikanta",
    author: "Sarat Chandra Chattopadhyay",
    publisher: "Sarat Samity",
    isbn: "9788170665463",
    edition: "Classic Reprint",
    pubDate: "2018-01-01",
    language: "Bengali",
    pages: 620,
    category: "bengali",
    tags: ["classic", "bengali literature", "sarat chandra"],
    price: 350,
    mrp: 500,
    rating: 4.8,
    ratingsCount: 5600,
    stock: 14,
    rare: true,
    coverHue: 65,
    description: "\u09B6\u09B0\u09CE\u099A\u09A8\u09CD\u09A6\u09CD\u09B0\u09C7\u09B0 \u0995\u09BE\u09B2\u099C\u09AF\u09BC\u09C0 \u0989\u09AA\u09A8\u09CD\u09AF\u09BE\u09B8 \u09B6\u09CD\u09B0\u09C0\u0995\u09BE\u09A8\u09CD\u09A4 \u2014 Sarat Chandra's timeless novel of a wanderer's encounters with unforgettable women like Rajlakshmi and Abhaya. A cornerstone of Bengali literature.",
    toc: ["\u09AA\u09CD\u09B0\u09A5\u09AE \u09AA\u09B0\u09CD\u09AC", "\u09A6\u09CD\u09AC\u09BF\u09A4\u09C0\u09AF\u09BC \u09AA\u09B0\u09CD\u09AC", "\u09A4\u09C3\u09A4\u09C0\u09AF\u09BC \u09AA\u09B0\u09CD\u09AC", "\u099A\u09A4\u09C1\u09B0\u09CD\u09A5 \u09AA\u09B0\u09CD\u09AC"],
    reviews: [rv("Madhumita Sen", 5, "\u099C\u09C0\u09AC\u09A8\u09C7\u09B0 \u09AC\u0987", "\u098F\u0995\u09BE\u09A7\u09BF\u0995\u09AC\u09BE\u09B0 \u09AA\u09A1\u09BC\u09C7\u099B\u09BF, \u09AA\u09CD\u09B0\u09A4\u09BF\u09AC\u09BE\u09B0 \u09A8\u09A4\u09C1\u09A8 \u09B2\u09BE\u0997\u09C7\u0964", "2025-08-20")]
  },
  {
    id: "b27",
    slug: "professor-shonku-samagra",
    title: "Professor Shonku Samagra",
    author: "Satyajit Ray",
    publisher: "Ananda Publishers",
    isbn: "9788170667740",
    edition: "Collected Edition",
    pubDate: "2019-01-01",
    language: "Bengali",
    pages: 1100,
    category: "bengali",
    tags: ["science fiction", "satyajit ray", "shonku"],
    price: 850,
    mrp: 1200,
    rating: 4.9,
    ratingsCount: 8900,
    stock: 21,
    trending: true,
    coverHue: 85,
    description: "\u0985\u09AC\u09BF\u09B6\u09CD\u09AC\u09BE\u09B8\u09CD\u09AF \u09AC\u09BF\u099C\u09CD\u099E\u09BE\u09A8\u09C0 \u09AA\u09CD\u09B0\u09AB\u09C7\u09B8\u09B0 \u09B6\u0999\u09CD\u0995\u09C1\u09B0 \u09B8\u0995\u09B2 \u0985\u09AD\u09BF\u09AF\u09BE\u09A8 \u2014 All Professor Shonku science fiction adventures in one collector's volume.",
    toc: ["\u09AC\u09CD\u09AF\u09CB\u09AE\u099A\u09BE\u0995\u09BE", "\u09B6\u0999\u09CD\u0995\u09C1\u09B0 \u09B8\u09CB\u09A8\u09BE\u09B0 \u0995\u09BE\u09A0\u09BF", "\u0995\u09B0\u09AD\u09BE\u09B8", "\u09AE\u09B9\u09BE\u0995\u09BE\u09B6\u09C7\u09B0 \u09A6\u09C7\u09B6\u09C7", "\u0989\u09A8"],
    reviews: [rv("Sourav Ganguly", 5, "Sci-fi before its time", "Ray imagined AI in the 60s. Genius.", "2025-10-10")]
  },
  {
    id: "b28",
    slug: "harry-potter-philosophers-stone",
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    publisher: "Bloomsbury",
    isbn: "9781408855652",
    edition: "Illustrated Paperback",
    pubDate: "2014-09-01",
    language: "English",
    pages: 352,
    category: "international",
    tags: ["fantasy", "young adult", "magic"],
    price: 399,
    mrp: 599,
    rating: 4.9,
    ratingsCount: 89100,
    stock: 76,
    bestseller: true,
    coverHue: 355,
    description: "The book that started it all. Harry Potter discovers he is a wizard and begins his first year at Hogwarts School of Witchcraft and Wizardry.",
    toc: ["The Boy Who Lived", "Diagon Alley", "The Journey from Platform Nine and Three-Quarters", "The Sorting Hat", "The Mirror of Erised"],
    reviews: [rv("Zara Khan", 5, "Magical", "Bought for my daughter, ended up re-reading myself.", "2025-12-05")]
  },
  {
    id: "b29",
    slug: "the-lord-of-the-rings-tolkien",
    title: "The Lord of the Rings (One Volume Edition)",
    author: "J.R.R. Tolkien",
    publisher: "HarperCollins",
    isbn: "9780261103252",
    edition: "50th Anniversary",
    pubDate: "2005-06-01",
    language: "English",
    pages: 1216,
    category: "international",
    tags: ["fantasy", "epic", "classic"],
    price: 799,
    mrp: 1299,
    rating: 4.8,
    ratingsCount: 52300,
    stock: 33,
    coverHue: 95,
    description: "Tolkien's epic masterpiece in a single volume \u2014 the Fellowship's quest to destroy the One Ring and defeat Sauron. The defining fantasy novel of the 20th century.",
    toc: ["The Fellowship of the Ring", "The Two Towers", "The Return of the King", "Appendices"],
    reviews: [rv("Aditya Pillai", 5, "Epic", "The worldbuilding is unmatched. Stunning edition.", "2025-09-01")]
  },
  {
    id: "b30",
    slug: "1984-george-orwell",
    title: "1984",
    author: "George Orwell",
    publisher: "Penguin Classics",
    isbn: "9780141439518",
    edition: "Penguin Classics",
    pubDate: "2003-01-01",
    language: "English",
    pages: 336,
    category: "international",
    tags: ["dystopia", "classic", "political"],
    price: 235,
    mrp: 350,
    rating: 4.7,
    ratingsCount: 47800,
    stock: 59,
    bestseller: true,
    coverHue: 240,
    description: "Orwell's chilling vision of a totalitarian future where Big Brother watches everything. More relevant today than ever \u2014 a warning about surveillance, propaganda and the manipulation of truth.",
    toc: ["Part One", "Part Two", "Part Three", "Appendix: The Principles of Newspeak"],
    reviews: [rv("Ritika Sharma", 5, "Terrifyingly relevant", "Read it once a year. Never gets old.", "2025-11-15")]
  },
  {
    id: "b31",
    slug: "the-kite-runner-khaled-hosseini",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    publisher: "Bloomsbury",
    isbn: "9781408824856",
    edition: "Paperback",
    pubDate: "2004-01-01",
    language: "English",
    pages: 384,
    category: "international",
    tags: ["literary fiction", "afghanistan"],
    price: 350,
    mrp: 550,
    rating: 4.7,
    ratingsCount: 36200,
    stock: 41,
    trending: true,
    coverHue: 15,
    description: "Amir and Hassan's friendship in 1970s Kabul is shattered by one act of betrayal. A devastating, unforgettable novel about guilt, redemption and the power of fathers and sons.",
    toc: ["Kabul", "The Kite Tournament", "America", "Return", "Redemption"],
    reviews: [rv("Neha Kulkarni", 5, "Heartbreaking", "Cried multiple times. For you, a thousand times over.", "2025-10-08")]
  },
  {
    id: "b32",
    slug: "to-kill-a-mockingbird-first-edition",
    title: "To Kill a Mockingbird \u2014 1960 First Edition Facsimile",
    author: "Harper Lee",
    publisher: "J.B. Lippincott (Facsimile)",
    isbn: "9780060935467",
    edition: "Facsimile Collector's Edition",
    pubDate: "1960-07-11",
    language: "English",
    pages: 324,
    category: "rare",
    tags: ["classic", "collectible", "first edition facsimile"],
    price: 2999,
    mrp: 4999,
    rating: 4.9,
    ratingsCount: 1240,
    stock: 3,
    rare: true,
    coverHue: 30,
    description: "A faithful facsimile of the 1960 first edition of Harper Lee's Pulitzer Prize-winning novel, with original dust jacket artwork. A collector's item for serious bibliophiles.",
    toc: ["Part One", "Part Two"],
    reviews: [rv("Vikram Mehta", 5, "Collector grade", "Arrived in pristine condition with archival wrapping.", "2025-09-27")]
  },
  {
    id: "b33",
    slug: "sherlock-holmes-complete-leatherbound",
    title: "The Complete Sherlock Holmes \u2014 Leatherbound Collector's Edition",
    author: "Arthur Conan Doyle",
    publisher: "Canterbury Classics",
    isbn: "9781607102113",
    edition: "Leatherbound",
    pubDate: "2011-10-01",
    language: "English",
    pages: 1096,
    category: "rare",
    tags: ["detective", "collectible", "leatherbound"],
    price: 1899,
    mrp: 2899,
    rating: 4.8,
    ratingsCount: 3120,
    stock: 7,
    rare: true,
    trending: true,
    coverHue: 260,
    description: "All four novels and 56 short stories of Sherlock Holmes in a bonded-leather collector's edition with gilded edges and ribbon marker.",
    toc: ["A Study in Scarlet", "The Sign of the Four", "The Adventures", "The Memoirs", "The Hound of the Baskervilles", "The Return", "The Valley of Fear"],
    reviews: [rv("Arundhati Das", 5, "Gorgeous binding", "Feels like an heirloom. Gift-wrapped beautifully.", "2025-12-16")]
  },
  {
    id: "b34",
    slug: "ncert-chemistry-class-11",
    title: "NCERT Chemistry Part I & II \u2014 Class 11",
    author: "NCERT",
    publisher: "NCERT",
    isbn: "9788174504944",
    edition: "2024 Edition",
    pubDate: "2024-03-01",
    language: "English",
    pages: 610,
    category: "school",
    tags: ["ncert", "cbse", "class 11", "chemistry"],
    price: 330,
    mrp: 360,
    rating: 4.6,
    ratingsCount: 11200,
    stock: 95,
    exam: "CBSE Boards",
    course: "Class 11",
    coverHue: 175,
    description: "Official NCERT Chemistry textbook for Class 11, essential for boards, JEE and NEET. Covers physical, inorganic and organic chemistry fundamentals.",
    toc: ["Some Basic Concepts of Chemistry", "Structure of Atom", "Periodic Table", "Chemical Bonding", "Thermodynamics", "Equilibrium", "Organic Chemistry Basics", "Hydrocarbons"],
    reviews: [rv("Harsh Vardhan", 5, "Genuine book", "Original NCERT print at a discount.", "2025-08-11")]
  },
  {
    id: "b35",
    slug: "icse-total-english-class-10",
    title: "ICSE Total English \u2014 Class 10",
    author: "Xavier Pinto, Selina",
    publisher: "Selina Publishers",
    isbn: "9788177662368",
    edition: "2025 Edition",
    pubDate: "2025-01-01",
    language: "English",
    pages: 480,
    category: "school",
    tags: ["icse", "english", "class 10"],
    price: 385,
    mrp: 475,
    rating: 4.5,
    ratingsCount: 4670,
    stock: 38,
    exam: "ICSE Boards",
    course: "Class 10",
    newRelease: true,
    coverHue: 205,
    description: "Complete English language and literature guide for ICSE Class 10 with grammar, composition, comprehension and specimen papers as per the latest CISCE syllabus.",
    toc: ["Grammar", "Composition", "Comprehension", "Letter Writing", "Specimen Papers"],
    reviews: [rv("Ira Chawla", 4, "ICSE aligned", "Matches the latest paper pattern.", "2026-01-05")]
  },
  {
    id: "b36",
    slug: "indian-economy-ramesh-singh",
    title: "Indian Economy",
    author: "Ramesh Singh",
    publisher: "McGraw Hill",
    isbn: "9789390185535",
    edition: "15th Edition",
    pubDate: "2024-06-01",
    language: "English",
    pages: 960,
    category: "competitive-exams",
    tags: ["upsc", "economy", "civil services"],
    price: 640,
    mrp: 995,
    rating: 4.6,
    ratingsCount: 14800,
    stock: 36,
    exam: "UPSC",
    bestseller: true,
    coverHue: 140,
    description: "The go-to book for Indian Economy for UPSC Prelims and Mains, updated with the latest budget, economic survey and policy developments.",
    toc: ["Introduction to Economics", "National Income", "Banking & Finance", "Inflation", "External Sector", "Agriculture", "Industry", "Budget & Fiscal Policy"],
    reviews: [rv("Prashant Jha", 5, "Updated edition", "Latest budget data included. UPSC-ready.", "2025-11-21")]
  },
  {
    id: "b37",
    slug: "modern-abc-physics-class-12",
    title: "Modern's ABC of Physics \u2014 Class 12",
    author: "S.P. Jauhar",
    publisher: "Modern Publishers",
    isbn: "9788178813368",
    edition: "2025 Edition",
    pubDate: "2025-03-01",
    language: "English",
    pages: 1240,
    category: "university",
    tags: ["physics", "reference", "plus two"],
    price: 890,
    mrp: 1250,
    rating: 4.4,
    ratingsCount: 3890,
    stock: 24,
    course: "B.Sc Physics",
    semester: "1st Year",
    newRelease: true,
    coverHue: 185,
    description: "Detailed physics reference bridging Class 12 and first-year B.Sc, with exhaustive theory, derivations and solved numericals.",
    toc: ["Electrostatics", "Current Electricity", "Magnetism", "EMI & AC", "Optics", "Modern Physics"],
    reviews: [rv("Shubham Tiwari", 4, "Detailed", "Good alternative when NCERT feels too brief.", "2025-12-28")]
  },
  {
    id: "b38",
    slug: "principles-of-economics-mankiw",
    title: "Principles of Economics",
    author: "N. Gregory Mankiw",
    publisher: "Cengage Learning",
    isbn: "9780357722718",
    edition: "9th Edition",
    pubDate: "2023-01-01",
    language: "English",
    pages: 880,
    category: "university",
    tags: ["economics", "bcom", "ba economics"],
    price: 925,
    mrp: 1395,
    rating: 4.6,
    ratingsCount: 5670,
    stock: 29,
    course: "B.A./B.Com Economics",
    semester: "1st Year",
    university: "Delhi University",
    trending: true,
    coverHue: 115,
    description: "The world's most popular economics textbook. Mankiw's ten principles and clear exposition make it the standard text for undergraduate economics courses across Indian universities.",
    toc: ["Ten Principles of Economics", "Supply and Demand", "Elasticity", "Consumer & Producer Theory", "Market Structures", "Macroeconomic Data", "Growth", "Money & Inflation", "Open Economy"],
    reviews: [rv("Sanjana Kapoor", 5, "Best intro to econ", "DU syllabus covered completely.", "2025-10-16")]
  },
  {
    id: "b39",
    slug: "let-us-c-yashavant-kanetkar",
    title: "Let Us C",
    author: "Yashavant Kanetkar",
    publisher: "BPB Publications",
    isbn: "9788183331630",
    edition: "19th Edition",
    pubDate: "2023-06-01",
    language: "English",
    pages: 560,
    category: "university",
    tags: ["c programming", "btech", "bca"],
    price: 340,
    mrp: 495,
    rating: 4.5,
    ratingsCount: 19300,
    stock: 64,
    course: "BCA/B.Tech",
    semester: "1st Year",
    bestseller: true,
    coverHue: 230,
    description: "India's bestselling C programming book for over two decades. Learn C from scratch with hundreds of examples and exercises \u2014 the first programming book for lakhs of students.",
    toc: ["Getting Started", "Decision Control", "Loops", "Functions", "Pointers", "Arrays & Strings", "Structures", "File I/O"],
    reviews: [rv("Gaurav Singh", 5, "Nostalgia + value", "Learned C from this 10 years ago, bought for my nephew.", "2025-09-05")]
  },
  {
    id: "b40",
    slug: "ikigai-hector-garcia",
    title: "Ikigai: The Japanese Secret to a Long and Happy Life",
    author: "H\xE9ctor Garc\xEDa, Francesc Miralles",
    publisher: "Penguin",
    isbn: "9780143130727",
    edition: "International Edition",
    pubDate: "2017-08-01",
    language: "English",
    pages: 208,
    category: "non-fiction",
    tags: ["philosophy", "japan", "wellbeing"],
    price: 329,
    mrp: 499,
    rating: 4.4,
    ratingsCount: 45600,
    stock: 71,
    bestseller: true,
    newRelease: false,
    coverHue: 200,
    description: "The international bestseller that reveals the Japanese concept of ikigai \u2014 your reason for being \u2014 through the lives of the world's longest-living people in Okinawa.",
    toc: ["Ikigai", "Anti-Aging Secrets", "From Logotherapy to Ikigai", "Find Flow in Everything You Do", "Lessons from Okinawa", "Gentle Movements", "Eat a Little Less"],
    reviews: [rv("Lakshmi Prasad", 4, "Calming read", "Gentle wisdom. Beautiful cover too.", "2025-11-25")]
  },
  {
    id: "b41",
    slug: "atomic-habits-hindi",
    title: "Atomic Habits (Hindi Edition)",
    author: "James Clear (Hindi Translation)",
    publisher: "Manjul Publishing",
    isbn: "9789390085638",
    edition: "Hindi Edition",
    pubDate: "2021-01-01",
    language: "Hindi",
    pages: 352,
    category: "non-fiction",
    tags: ["habits", "hindi", "self-help"],
    price: 275,
    mrp: 399,
    rating: 4.5,
    ratingsCount: 12300,
    stock: 46,
    newRelease: true,
    coverHue: 50,
    description: "Atomic Habits \u0915\u093E \u0906\u0927\u093F\u0915\u093E\u0930\u093F\u0915 \u0939\u093F\u0902\u0926\u0940 \u0905\u0928\u0941\u0935\u093E\u0926 \u2014 \u091B\u094B\u091F\u0940 \u0906\u0926\u0924\u0947\u0902, \u0905\u0938\u093E\u0927\u093E\u0930\u0923 \u092A\u0930\u093F\u0923\u093E\u092E\u0964 James Clear's classic, now in Hindi.",
    toc: ["\u092E\u0942\u0932 \u0938\u093F\u0926\u094D\u0927\u093E\u0902\u0924", "\u092A\u0939\u0932\u093E \u0928\u093F\u092F\u092E", "\u0926\u0942\u0938\u0930\u093E \u0928\u093F\u092F\u092E", "\u0924\u0940\u0938\u0930\u093E \u0928\u093F\u092F\u092E", "\u091A\u094C\u0925\u093E \u0928\u093F\u092F\u092E"],
    reviews: [rv("Ramesh Gupta", 5, "\u092C\u0947\u0939\u0924\u0930\u0940\u0928 \u0905\u0928\u0941\u0935\u093E\u0926", "\u0939\u093F\u0902\u0926\u0940 \u092E\u0947\u0902 \u092A\u0922\u093C\u0915\u0930 \u0914\u0930 \u092D\u0940 \u0905\u091A\u094D\u091B\u093E \u0932\u0917\u093E\u0964", "2025-12-08")]
  },
  {
    id: "b42",
    slug: "gate-computer-science-papers",
    title: "GATE 2026 Computer Science \u2014 39 Years Solved Papers",
    author: "GK Publications",
    publisher: "GKP",
    isbn: "9789391520578",
    edition: "2026 Edition",
    pubDate: "2025-09-01",
    language: "English",
    pages: 1140,
    category: "competitive-exams",
    tags: ["gate", "computer science", "solved papers"],
    price: 720,
    mrp: 1095,
    rating: 4.4,
    ratingsCount: 3450,
    stock: 33,
    exam: "GATE",
    newRelease: true,
    coverHue: 255,
    description: "Chapter-wise solved GATE CS papers from 1987\u20132025 with detailed solutions, topic weightage analysis and free online mock tests.",
    toc: ["Digital Logic", "Computer Organization", "Programming & DS", "Algorithms", "Theory of Computation", "Compiler Design", "Operating Systems", "Databases", "Networks", "General Aptitude"],
    reviews: [rv("Vivek Anand", 4, "GATE-ready", "Solutions are crisp. The weightage charts help plan.", "2025-12-20")]
  },
  {
    id: "b43",
    slug: "pharmacology-kd-tripathi",
    title: "Essentials of Medical Pharmacology",
    author: "K.D. Tripathi",
    publisher: "Jaypee Brothers",
    isbn: "9789352704996",
    edition: "8th Edition",
    pubDate: "2023-01-01",
    language: "English",
    pages: 1032,
    category: "medical",
    tags: ["pharmacology", "mbbs", "second year"],
    price: 1150,
    mrp: 1695,
    rating: 4.7,
    ratingsCount: 6890,
    stock: 19,
    course: "MBBS",
    semester: "2nd Year",
    bestseller: true,
    coverHue: 175,
    description: "India's most trusted pharmacology textbook \u2014 rational drug therapy, classification tables and exam-focused presentation for MBBS second professional.",
    toc: ["General Pharmacology", "Autonomic Nervous System", "CNS Drugs", "Cardiovascular Drugs", "Antimicrobials", "Endocrine Pharmacology", "Chemotherapy"],
    reviews: [rv("Dr. Nisha Rao", 5, "MBBS standard", "Tables make revision so fast. Jaypee original.", "2025-11-08")]
  },
  {
    id: "b44",
    slug: "panchatantra-classic-tales",
    title: "Panchatantra: The Complete Classic Tales",
    author: "Vishnu Sharma (Retold)",
    publisher: "Om Books",
    isbn: "9789380069893",
    edition: "Illustrated Edition",
    pubDate: "2019-01-01",
    language: "English",
    pages: 240,
    category: "school",
    tags: ["children", "stories", "moral tales"],
    price: 195,
    mrp: 299,
    rating: 4.6,
    ratingsCount: 7210,
    stock: 83,
    coverHue: 60,
    description: "The complete Panchatantra with beautiful illustrations \u2014 timeless animal fables of wisdom, friendship and cleverness that have taught children for 2,000 years.",
    toc: ["Mitra Bheda", "Mitra Samprapti", "Kakolukiyam", "Labdhapranasham", "Aparikshitakarakam"],
    reviews: [rv("Geeta Nair", 5, "Kids loved it", "My 7-year-old asks for one story every night.", "2025-10-30")]
  },
  {
    id: "b45",
    slug: "ghotoner-bhitor-ghoton-byomkesh",
    title: "Byomkesh Bakshi Samagra",
    author: "Sharadindu Bandyopadhyay",
    publisher: "Ananda Publishers",
    isbn: "9788170662257",
    edition: "Collected Edition",
    pubDate: "2016-01-01",
    language: "Bengali",
    pages: 1300,
    category: "bengali",
    tags: ["detective", "byomkesh", "bengali"],
    price: 950,
    mrp: 1400,
    rating: 4.8,
    ratingsCount: 6300,
    stock: 16,
    rare: true,
    coverHue: 15,
    description: "\u09AC\u09CD\u09AF\u09CB\u09AE\u0995\u09C7\u09B6 \u09AC\u0995\u09CD\u09B8\u09C0\u09B0 \u09B8\u09AE\u09B8\u09CD\u09A4 \u0997\u09CB\u09AF\u09BC\u09C7\u09A8\u09CD\u09A6\u09BE \u0995\u09BE\u09B9\u09BF\u09A8\u09C0\u09B0 \u09B8\u0982\u0995\u09B2\u09A8 \u2014 The complete Byomkesh Bakshi detective stories by Sharadindu Bandyopadhyay in one handsome volume.",
    toc: ["\u09B8\u09A4\u09CD\u09AF\u09BE\u09A8\u09CD\u09AC\u09C7\u09B7\u09C0", "\u09AA\u09C8\u09A4\u09C3\u0995 \u09B8\u09C2\u09A4\u09CD\u09B0", "\u09B0\u0995\u09CD\u09A4\u09AE\u09C1\u0996\u09C0 \u09A8\u09C0\u09B2\u09BE", "\u099A\u09BF\u09A4\u09CD\u09B0\u099A\u09CB\u09B0", "\u0985\u0997\u09CD\u09A8\u09BF\u09AC\u09BE\u09A3"],
    reviews: [rv("Koushik Dutta", 5, "\u09B8\u09A4\u09CD\u09AF\u09BF\u0995\u09BE\u09B0\u09C7\u09B0 \u09B0\u09A4\u09CD\u09A8", "\u0986\u09A8\u09A8\u09CD\u09A6\u09C7\u09B0 \u099B\u09BE\u09AA\u09BE \u09B8\u09AC\u09B8\u09AE\u09AF\u09BC \u09AD\u09BE\u09B2\u09CB\u0964 \u09A6\u09CD\u09B0\u09C1\u09A4 \u09A1\u09C7\u09B2\u09BF\u09AD\u09BE\u09B0\u09BF\u0964", "2025-09-19")]
  },
  {
    id: "b46",
    slug: "thinking-fast-and-slow",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    publisher: "Penguin",
    isbn: "9780141033570",
    edition: "International Edition",
    pubDate: "2012-04-01",
    language: "English",
    pages: 512,
    category: "non-fiction",
    tags: ["psychology", "decision making", "nobel laureate"],
    price: 499,
    mrp: 799,
    rating: 4.5,
    ratingsCount: 28700,
    stock: 37,
    coverHue: 215,
    description: "Nobel laureate Daniel Kahneman takes us on a tour of the mind \u2014 the fast, intuitive System 1 and the slow, logical System 2 \u2014 and reveals how our choices are shaped by biases we never notice.",
    toc: ["Two Systems", "Heuristics and Biases", "Overconfidence", "Choices", "Two Selves"],
    reviews: [rv("Aditya Menon", 5, "Dense but rewarding", "Took me two months. Worth every page.", "2025-08-27")]
  },
  {
    id: "b47",
    slug: "operating-system-concepts-galvin",
    title: "Operating System Concepts",
    author: "Silberschatz, Galvin, Gagne",
    publisher: "Wiley",
    isbn: "9781119800361",
    edition: "10th Edition",
    pubDate: "2022-01-01",
    language: "English",
    pages: 976,
    category: "engineering",
    tags: ["operating systems", "computer science", "btech"],
    price: 795,
    mrp: 1195,
    rating: 4.6,
    ratingsCount: 5980,
    stock: 26,
    course: "B.Tech CSE",
    semester: "3rd Year",
    university: "Anna University",
    newRelease: true,
    coverHue: 275,
    description: 'The "dinosaur book" \u2014 the standard OS text covering processes, threads, scheduling, synchronization, deadlocks, memory management and file systems.',
    toc: ["Introduction", "Processes", "Threads & Concurrency", "CPU Scheduling", "Deadlocks", "Memory Management", "Virtual Memory", "File Systems", "Security"],
    reviews: [rv("Priyanka Das", 4, "University standard", "Matches our syllabus exactly. Wiley India print.", "2025-12-12")]
  },
  {
    id: "b48",
    slug: "the-almanack-of-naval-ravikant",
    title: "The Almanack of Naval Ravikant",
    author: "Eric Jorgenson",
    publisher: "Harper Business",
    isbn: "9780063312707",
    edition: "Paperback",
    pubDate: "2020-09-15",
    language: "English",
    pages: 288,
    category: "non-fiction",
    tags: ["wealth", "happiness", "startups"],
    price: 399,
    mrp: 599,
    rating: 4.7,
    ratingsCount: 19800,
    stock: 49,
    trending: true,
    newRelease: true,
    coverHue: 235,
    description: "A curated collection of Naval Ravikant's wisdom on building wealth and finding happiness \u2014 drawn from his tweets, podcasts and essays. Specific knowledge, leverage and judgment, distilled.",
    toc: ["Building Wealth", "Building Judgment", "Learning Happiness", "Saving Yourself", "Philosophy"],
    reviews: [rv("Ishaan Malhotra", 5, "Re-read monthly", "Every page is quotable.", "2026-01-10")]
  }
];
var getBook = (slug) => BOOKS.find((b) => b.slug === slug);
var byCategory = (cat) => BOOKS.filter((b) => b.category === cat);
var discountPct = (b) => Math.round((b.mrp - b.price) / b.mrp * 100);
var formatINR = (n) => "\u20B9" + n.toLocaleString("en-IN");
